### ISSUE TITLE
udio在智能电视上无法自动播放音频

### ISSUE THREAD

**Issue by silencyXiao** [MauriceButler/simple-audio#3]
你好，我也遇到了这个问题，audio在部分移动设备上无法自动播放音频的问题；我这个是放到智能电视上，电视定时自动推送消息，完全不能有交互的！
想请教你如何解决的！如果可以希望可以加下我QQ 1048502815，谢谢
这个是我的测试地址 http://www.op110.com/tv/tts.html

**Comment by MauriceButler** [comment]
Hello,
If you can not have interactions on the smart TV, I am sorry but I do not think this library will be able to help you.
